project_id = "nskulyhcaogrfekojyyb"

[functions.schedule-meeting-reminders]
verify_jwt = false

[functions.mobile-money-webhook]
verify_jwt = false

[functions.check-late-payments]
verify_jwt = false

[functions.send-birth-visit-reminders]
verify_jwt = false

[functions.send-event-reminders]
verify_jwt = false

[functions.family-chatbot]
verify_jwt = false
